export const PAGE_CONFIG = [
    {
        title:'写在前面',
        children:[
            {
                name:'developer_greeting',
                title:'开发者寄语',
                url:'/read/developer_greeting',
                sections:[  ]
            }
        ]
    },
    // {
    //     title:'校内资源',
    //     children:[
    //         {
    //             name:'quick_links',
    //             title:'快速连接',
    //             url:'/read/quick_links'
    //         },{
    //             name:'campus_chat',
    //             title:'校内群聊',
    //             url:'/read/campus_chat'
    //         }
    //     ]
    // },
    {
        title:'生活出行',
        children:[
            {
                name:'medical_reimbursement',
                title:'医疗与报销',
                url:'/read/medical_reimbursement',
                sections:[
                    {
                        href:'#title1',
                        title:'一、校内就医'
                    },{
                        href:'#title2',
                        title:'二、校外就医'
                    },{
                        href:'#title3',
                        title:'三、其他内容'
                    },
                ]
            },{
                name:'campus_card_service',
                title:'校园卡业务',
                url:'/read/campus_card_service',
                sections:[
                    {
                        href:'#title1',
                        title:'一、校园卡简介'
                    },{
                        href:'#title2',
                        title:'二、校园卡补办'
                    },{
                        href:'#title3',
                        title:'三、圈存与充值'
                    },{
                        href:'#title4',
                        title:'四、消费限额与余额查询'
                    },{
                        href:'#title5',
                        title:'五、二维码快捷支付'
                    },
                ]
            },{
                name:'campus_network',
                title:'校园网',
                url:'/read/campus_network',
                sections:[
                    {
                        href:'#title1',
                        title:'一、基本情况'
                    },{
                        href:'#title2',
                        title:'二、连接方式'
                    },{
                        href:'#title4',
                        title:'三、收费标准'
                    },{
                        href:'#title5',
                        title:'四、进阶使用'
                    },
                ]
            }
        ]
    },{
        title:'学在东大',
        children:[
            {
                name:'basic_academic_info',
                title:'基础学业信息',
                url:'/read/basic_academic_info',
                sections:[
                    {
                        href:'#title1',
                        title:'一、学分'
                    },{
                        href:'#title2',
                        title:'二、成绩'
                    },{
                        href:'#title3',
                        title:'三、GPA'
                    },
                ]
            },{
                name:'computer_based_exam_guide',
                title:'机考指南',
                url:'/read/computer_based_exam_guide',
                sections:[
                    {
                        href:'#title1',
                        title:'一、考试流程'
                    },{
                        href:'#title2',
                        title:'二、注意事项'
                    }
                ]
            },{
                name:'recommendation_exemption',
                title:'推免（保研）',
                url:'/read/recommendation_exemption',
                sections:[
                    {
                        href:'#title1',
                        title:'一、保研简介'
                    },{
                        href:'#title2',
                        title:'二、学业成绩保研'
                    },{
                        href:'#title3',
                        title:'三、辅导员保研'
                    },{
                        href:'#title4',
                        title:'四、支教保研'
                    },{
                        href:'#title5',
                        title:'五、工程硕博保研'
                    }
                ]
            },{
                name:'general_courses',
                title:'公共课',
                url:'/read/general_courses',
                sections:[
                    {
                        href:'#title1',
                        title:'一、高等数学'
                    }
                ]
            },{
                name:'competitions',
                title:'竞赛',
                url:'/read/competitions',
                sections:[
                    {
                        href:'#title1',
                        title:'一、部分竞赛时间线'
                    }, {
                        href:'#title2',
                        title:'二、相关信息发布渠道'
                    },{
                        href:'#title3',
                        title:'三、结合大创参加竞赛'
                    }
                ]
            },{
                name:'selected_trainee',
                title:'选调',
                url:'/read/selected_trainee',
                sections:[
                    {
                        href:'#title1',
                        title:'一、辽宁定向选调'
                    }
                ]
            }
        ]
    }
]